name: Sync LeetCode Solutions

on:
  workflow_dispatch:

  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.xVaGPmnudM7rIqkJFe2Qn32rNlkkqUeo }}
          leetcode-session: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfYXV0aF91c2VyX2lkIjoiMTAzNzc2MDQiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjQzYjBlM2JiMWI1OWEzMjFjMjA0YzA0YzFmMDI2ZDJjMDFiMTQzNjRiZjE0Yjc0N2E1ZGQzYzgxM2YxZTIxMTQiLCJzZXNzaW9uX3V1aWQiOiJjY2I2OWI1MSIsImlkIjoxMDM3NzYwNCwiZW1haWwiOiIyMzAwMDMyODI2QGtsdW5pdmVyc2l0eS5pbiIsInVzZXJuYW1lIjoicGFydGgyMDk5IiwidXNlcl9zbHVnIjoicGFydGgyMDk5IiwiYXZhdGFyIjoiaHR0cHM6Ly9hc3NldHMubGVldGNvZGUuY29tL3VzZXJzL3BhcnRoMjA5OS9hdmF0YXJfMTc1NDg4NDI5OC5wbmciLCJyZWZyZXNoZWRfYXQiOjE3OTA3NDI1NDAsImlwIjoiNDUuMjQ5Ljc5LjQ1IiwiaWRlbnRpdHkiOiJjMDYwNTI4YTAzYTYzYjFiYzFiMGQxZmRmMmE4OGNmZSIsImRldmljZV93aXRoX2lwIjpbIjZiZjQ2YzAxZmI2MDBiMWFhYzIwN2YyYTljYmM5OTNmIiwiNDUuMjQ5Ljc5LjQ1Il0sIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.JYYQbVypOSWSozMHc3Uob7JeQdwbbl4QorXDnatv6jE }}
          destination-folder: solutions
          verbose: true
          commit-header: "[LeetCode Sync]"